[package]
edition.workspace = true
name = "ring-cavp"
publish = false
rust-version.workspace = true
version = "0.1.0"

[dev-dependencies]
ring = { workspace = true }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dev-dependencies]
wasm-bindgen-test = { workspace = true }
